import { Toaster } from "react-hot-toast";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className="min-h-screen  h-screen  ">
      <Toaster
  position="top-right"
  reverseOrder={false}
/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
