import Header from "@/components/ui/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-y-hidden">
        <Header />
        {children}
      </body>
    </html>
  );
}
